services:
  redis:
    image: redis:7.2
    container_name: my_redis
    ports:
      - "6379:6379"

  nginx:
    image: nginx:1.27
    container_name: my_nginx
    ports:
      - "9090:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro